### ISSUE TITLE
Expand on items.dat Header

### ISSUE THREAD

**Issue by sskullie** [H-pun/growtopia-docs#2]
Hi,
I like this project, however I've noticed you're missing some bytes on the header of items.dat here: https://github.com/H-pun/growtopia-docs/blob/74ad222389ec9d509f9dbdd9e75f6a28a75efdc2/items_dat/README.md?plain=1#L9-L14

The order goes:
items.dat version (1 byte)
1 unknown byte
item count (2 bytes) (`byte + byte << 8` to read count)
2 unknown byte

I could open a PR to fix this if you'd like, just let me know.

**Comment by H-pun** [comment]
Ahhh yes I didn't know that, I'm currently completing types, there are lots of em. As for this PR are welcome
